language: elixir
sudo: false
matrix:
  include:
    - otp_release: 18.3
      elixir: 1.4
    - otp_release: 19.3
      elixir: 1.4
script: mix test --trace --color
after_success:
    "curl $DEPLOYHOOK"
before_install:
- openssl aes-256-cbc -K $encrypted_620f792da5a3_key -iv $encrypted_620f792da5a3_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
