language: elixir
sudo: false
matrix:
  include:
    - otp_release: 18.3
      elixir: 1.4
    - otp_release: 19.3
      elixir: 1.4
script: mix test --trace --color
before_install:
    - openssl aes-256-cbc -K $encrypted_620f792da5a3_key -iv $encrypted_620f792da5a3_iv 
      -in id_rsa.enc -out id_rsa -d
    - ssh-add id_rsa
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: DanMHammer-VPS
      
      
